import * as React from 'react'
import { Check, ChevronsUpDown, MapPin, X } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'

// ---------------------------------------------------------------------------
// County data — expand as needed for your territory coverage
// Format: { county: string; state: string; stateCode: string }
// ---------------------------------------------------------------------------
export const US_COUNTIES: Array<{
  county: string
  state: string
  stateCode: string
}> = [
  // Nebraska
  { county: 'Adams', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Antelope', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Arthur', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Banner', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Blaine', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Boone', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Box Butte', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Boyd', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Brown', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Buffalo', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Burt', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Butler', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Cass', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Cedar', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Chase', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Cherry', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Cheyenne', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Clay', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Colfax', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Cuming', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Custer', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Dakota', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Dawes', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Dawson', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Deuel', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Dixon', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Dodge', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Douglas', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Dundy', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Fillmore', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Franklin', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Frontier', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Furnas', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Gage', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Garden', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Garfield', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Gosper', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Grant', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Greeley', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Hall', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Hamilton', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Harlan', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Hayes', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Hitchcock', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Holt', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Hooker', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Howard', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Jefferson', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Johnson', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Kearney', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Keith', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Keya Paha', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Kimball', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Knox', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Lancaster', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Lincoln', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Logan', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Loup', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Madison', state: 'Nebraska', stateCode: 'NE' },
  { county: 'McPherson', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Merrick', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Morrill', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Nance', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Nemaha', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Nuckolls', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Otoe', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Pawnee', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Perkins', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Phelps', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Pierce', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Platte', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Polk', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Red Willow', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Richardson', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Rock', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Saline', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Sarpy', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Saunders', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Scotts Bluff', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Seward', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Sheridan', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Sherman', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Sioux', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Stanton', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Thayer', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Thomas', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Thurston', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Valley', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Washington', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Wayne', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Webster', state: 'Nebraska', stateCode: 'NE' },
  { county: 'Wheeler', state: 'Nebraska', stateCode: 'NE' },
  { county: 'York', state: 'Nebraska', stateCode: 'NE' },

  // Iowa
  { county: 'Adair', state: 'Iowa', stateCode: 'IA' },
  { county: 'Adams', state: 'Iowa', stateCode: 'IA' },
  { county: 'Allamakee', state: 'Iowa', stateCode: 'IA' },
  { county: 'Appanoose', state: 'Iowa', stateCode: 'IA' },
  { county: 'Audubon', state: 'Iowa', stateCode: 'IA' },
  { county: 'Benton', state: 'Iowa', stateCode: 'IA' },
  { county: 'Black Hawk', state: 'Iowa', stateCode: 'IA' },
  { county: 'Boone', state: 'Iowa', stateCode: 'IA' },
  { county: 'Bremer', state: 'Iowa', stateCode: 'IA' },
  { county: 'Buchanan', state: 'Iowa', stateCode: 'IA' },
  { county: 'Buena Vista', state: 'Iowa', stateCode: 'IA' },
  { county: 'Butler', state: 'Iowa', stateCode: 'IA' },
  { county: 'Calhoun', state: 'Iowa', stateCode: 'IA' },
  { county: 'Carroll', state: 'Iowa', stateCode: 'IA' },
  { county: 'Cass', state: 'Iowa', stateCode: 'IA' },
  { county: 'Cedar', state: 'Iowa', stateCode: 'IA' },
  { county: 'Cerro Gordo', state: 'Iowa', stateCode: 'IA' },
  { county: 'Cherokee', state: 'Iowa', stateCode: 'IA' },
  { county: 'Chickasaw', state: 'Iowa', stateCode: 'IA' },
  { county: 'Clarke', state: 'Iowa', stateCode: 'IA' },
  { county: 'Clay', state: 'Iowa', stateCode: 'IA' },
  { county: 'Clayton', state: 'Iowa', stateCode: 'IA' },
  { county: 'Clinton', state: 'Iowa', stateCode: 'IA' },
  { county: 'Crawford', state: 'Iowa', stateCode: 'IA' },
  { county: 'Dallas', state: 'Iowa', stateCode: 'IA' },
  { county: 'Davis', state: 'Iowa', stateCode: 'IA' },
  { county: 'Decatur', state: 'Iowa', stateCode: 'IA' },
  { county: 'Delaware', state: 'Iowa', stateCode: 'IA' },
  { county: 'Des Moines', state: 'Iowa', stateCode: 'IA' },
  { county: 'Dickinson', state: 'Iowa', stateCode: 'IA' },
  { county: 'Dubuque', state: 'Iowa', stateCode: 'IA' },
  { county: 'Emmet', state: 'Iowa', stateCode: 'IA' },
  { county: 'Fayette', state: 'Iowa', stateCode: 'IA' },
  { county: 'Floyd', state: 'Iowa', stateCode: 'IA' },
  { county: 'Franklin', state: 'Iowa', stateCode: 'IA' },
  { county: 'Fremont', state: 'Iowa', stateCode: 'IA' },
  { county: 'Greene', state: 'Iowa', stateCode: 'IA' },
  { county: 'Grundy', state: 'Iowa', stateCode: 'IA' },
  { county: 'Guthrie', state: 'Iowa', stateCode: 'IA' },
  { county: 'Hamilton', state: 'Iowa', stateCode: 'IA' },
  { county: 'Hancock', state: 'Iowa', stateCode: 'IA' },
  { county: 'Hardin', state: 'Iowa', stateCode: 'IA' },
  { county: 'Harrison', state: 'Iowa', stateCode: 'IA' },
  { county: 'Henry', state: 'Iowa', stateCode: 'IA' },
  { county: 'Howard', state: 'Iowa', stateCode: 'IA' },
  { county: 'Humboldt', state: 'Iowa', stateCode: 'IA' },
  { county: 'Ida', state: 'Iowa', stateCode: 'IA' },
  { county: 'Iowa', state: 'Iowa', stateCode: 'IA' },
  { county: 'Jackson', state: 'Iowa', stateCode: 'IA' },
  { county: 'Jasper', state: 'Iowa', stateCode: 'IA' },
  { county: 'Jefferson', state: 'Iowa', stateCode: 'IA' },
  { county: 'Johnson', state: 'Iowa', stateCode: 'IA' },
  { county: 'Jones', state: 'Iowa', stateCode: 'IA' },
  { county: 'Keokuk', state: 'Iowa', stateCode: 'IA' },
  { county: 'Kossuth', state: 'Iowa', stateCode: 'IA' },
  { county: 'Lee', state: 'Iowa', stateCode: 'IA' },
  { county: 'Linn', state: 'Iowa', stateCode: 'IA' },
  { county: 'Louisa', state: 'Iowa', stateCode: 'IA' },
  { county: 'Lucas', state: 'Iowa', stateCode: 'IA' },
  { county: 'Lyon', state: 'Iowa', stateCode: 'IA' },
  { county: 'Madison', state: 'Iowa', stateCode: 'IA' },
  { county: 'Mahaska', state: 'Iowa', stateCode: 'IA' },
  { county: 'Marion', state: 'Iowa', stateCode: 'IA' },
  { county: 'Marshall', state: 'Iowa', stateCode: 'IA' },
  { county: 'Mills', state: 'Iowa', stateCode: 'IA' },
  { county: 'Mitchell', state: 'Iowa', stateCode: 'IA' },
  { county: 'Monona', state: 'Iowa', stateCode: 'IA' },
  { county: 'Monroe', state: 'Iowa', stateCode: 'IA' },
  { county: 'Montgomery', state: 'Iowa', stateCode: 'IA' },
  { county: 'Muscatine', state: 'Iowa', stateCode: 'IA' },
  { county: "O'Brien", state: 'Iowa', stateCode: 'IA' },
  { county: 'Osceola', state: 'Iowa', stateCode: 'IA' },
  { county: 'Page', state: 'Iowa', stateCode: 'IA' },
  { county: 'Palo Alto', state: 'Iowa', stateCode: 'IA' },
  { county: 'Plymouth', state: 'Iowa', stateCode: 'IA' },
  { county: 'Pocahontas', state: 'Iowa', stateCode: 'IA' },
  { county: 'Polk', state: 'Iowa', stateCode: 'IA' },
  { county: 'Pottawattamie', state: 'Iowa', stateCode: 'IA' },
  { county: 'Poweshiek', state: 'Iowa', stateCode: 'IA' },
  { county: 'Ringgold', state: 'Iowa', stateCode: 'IA' },
  { county: 'Sac', state: 'Iowa', stateCode: 'IA' },
  { county: 'Scott', state: 'Iowa', stateCode: 'IA' },
  { county: 'Shelby', state: 'Iowa', stateCode: 'IA' },
  { county: 'Sioux', state: 'Iowa', stateCode: 'IA' },
  { county: 'Story', state: 'Iowa', stateCode: 'IA' },
  { county: 'Tama', state: 'Iowa', stateCode: 'IA' },
  { county: 'Taylor', state: 'Iowa', stateCode: 'IA' },
  { county: 'Union', state: 'Iowa', stateCode: 'IA' },
  { county: 'Van Buren', state: 'Iowa', stateCode: 'IA' },
  { county: 'Wapello', state: 'Iowa', stateCode: 'IA' },
  { county: 'Warren', state: 'Iowa', stateCode: 'IA' },
  { county: 'Washington', state: 'Iowa', stateCode: 'IA' },
  { county: 'Wayne', state: 'Iowa', stateCode: 'IA' },
  { county: 'Webster', state: 'Iowa', stateCode: 'IA' },
  { county: 'Winnebago', state: 'Iowa', stateCode: 'IA' },
  { county: 'Winneshiek', state: 'Iowa', stateCode: 'IA' },
  { county: 'Woodbury', state: 'Iowa', stateCode: 'IA' },
  { county: 'Worth', state: 'Iowa', stateCode: 'IA' },
  { county: 'Wright', state: 'Iowa', stateCode: 'IA' },

  // Kansas
  { county: 'Allen', state: 'Kansas', stateCode: 'KS' },
  { county: 'Anderson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Atchison', state: 'Kansas', stateCode: 'KS' },
  { county: 'Barber', state: 'Kansas', stateCode: 'KS' },
  { county: 'Barton', state: 'Kansas', stateCode: 'KS' },
  { county: 'Bourbon', state: 'Kansas', stateCode: 'KS' },
  { county: 'Brown', state: 'Kansas', stateCode: 'KS' },
  { county: 'Butler', state: 'Kansas', stateCode: 'KS' },
  { county: 'Chase', state: 'Kansas', stateCode: 'KS' },
  { county: 'Chautauqua', state: 'Kansas', stateCode: 'KS' },
  { county: 'Cherokee', state: 'Kansas', stateCode: 'KS' },
  { county: 'Cheyenne', state: 'Kansas', stateCode: 'KS' },
  { county: 'Clark', state: 'Kansas', stateCode: 'KS' },
  { county: 'Clay', state: 'Kansas', stateCode: 'KS' },
  { county: 'Cloud', state: 'Kansas', stateCode: 'KS' },
  { county: 'Coffey', state: 'Kansas', stateCode: 'KS' },
  { county: 'Comanche', state: 'Kansas', stateCode: 'KS' },
  { county: 'Cowley', state: 'Kansas', stateCode: 'KS' },
  { county: 'Crawford', state: 'Kansas', stateCode: 'KS' },
  { county: 'Decatur', state: 'Kansas', stateCode: 'KS' },
  { county: 'Dickinson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Doniphan', state: 'Kansas', stateCode: 'KS' },
  { county: 'Douglas', state: 'Kansas', stateCode: 'KS' },
  { county: 'Edwards', state: 'Kansas', stateCode: 'KS' },
  { county: 'Elk', state: 'Kansas', stateCode: 'KS' },
  { county: 'Ellis', state: 'Kansas', stateCode: 'KS' },
  { county: 'Ellsworth', state: 'Kansas', stateCode: 'KS' },
  { county: 'Finney', state: 'Kansas', stateCode: 'KS' },
  { county: 'Ford', state: 'Kansas', stateCode: 'KS' },
  { county: 'Franklin', state: 'Kansas', stateCode: 'KS' },
  { county: 'Geary', state: 'Kansas', stateCode: 'KS' },
  { county: 'Gove', state: 'Kansas', stateCode: 'KS' },
  { county: 'Graham', state: 'Kansas', stateCode: 'KS' },
  { county: 'Grant', state: 'Kansas', stateCode: 'KS' },
  { county: 'Gray', state: 'Kansas', stateCode: 'KS' },
  { county: 'Greeley', state: 'Kansas', stateCode: 'KS' },
  { county: 'Greenwood', state: 'Kansas', stateCode: 'KS' },
  { county: 'Hamilton', state: 'Kansas', stateCode: 'KS' },
  { county: 'Harper', state: 'Kansas', stateCode: 'KS' },
  { county: 'Harvey', state: 'Kansas', stateCode: 'KS' },
  { county: 'Haskell', state: 'Kansas', stateCode: 'KS' },
  { county: 'Hodgeman', state: 'Kansas', stateCode: 'KS' },
  { county: 'Jackson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Jefferson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Jewell', state: 'Kansas', stateCode: 'KS' },
  { county: 'Johnson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Kearny', state: 'Kansas', stateCode: 'KS' },
  { county: 'Kingman', state: 'Kansas', stateCode: 'KS' },
  { county: 'Kiowa', state: 'Kansas', stateCode: 'KS' },
  { county: 'Labette', state: 'Kansas', stateCode: 'KS' },
  { county: 'Lane', state: 'Kansas', stateCode: 'KS' },
  { county: 'Leavenworth', state: 'Kansas', stateCode: 'KS' },
  { county: 'Lincoln', state: 'Kansas', stateCode: 'KS' },
  { county: 'Linn', state: 'Kansas', stateCode: 'KS' },
  { county: 'Logan', state: 'Kansas', stateCode: 'KS' },
  { county: 'Lyon', state: 'Kansas', stateCode: 'KS' },
  { county: 'Marion', state: 'Kansas', stateCode: 'KS' },
  { county: 'Marshall', state: 'Kansas', stateCode: 'KS' },
  { county: 'McPherson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Meade', state: 'Kansas', stateCode: 'KS' },
  { county: 'Miami', state: 'Kansas', stateCode: 'KS' },
  { county: 'Mitchell', state: 'Kansas', stateCode: 'KS' },
  { county: 'Montgomery', state: 'Kansas', stateCode: 'KS' },
  { county: 'Morris', state: 'Kansas', stateCode: 'KS' },
  { county: 'Morton', state: 'Kansas', stateCode: 'KS' },
  { county: 'Nemaha', state: 'Kansas', stateCode: 'KS' },
  { county: 'Neosho', state: 'Kansas', stateCode: 'KS' },
  { county: 'Ness', state: 'Kansas', stateCode: 'KS' },
  { county: 'Norton', state: 'Kansas', stateCode: 'KS' },
  { county: 'Osage', state: 'Kansas', stateCode: 'KS' },
  { county: 'Osborne', state: 'Kansas', stateCode: 'KS' },
  { county: 'Ottawa', state: 'Kansas', stateCode: 'KS' },
  { county: 'Pawnee', state: 'Kansas', stateCode: 'KS' },
  { county: 'Phillips', state: 'Kansas', stateCode: 'KS' },
  { county: 'Pottawatomie', state: 'Kansas', stateCode: 'KS' },
  { county: 'Pratt', state: 'Kansas', stateCode: 'KS' },
  { county: 'Rawlins', state: 'Kansas', stateCode: 'KS' },
  { county: 'Reno', state: 'Kansas', stateCode: 'KS' },
  { county: 'Republic', state: 'Kansas', stateCode: 'KS' },
  { county: 'Rice', state: 'Kansas', stateCode: 'KS' },
  { county: 'Riley', state: 'Kansas', stateCode: 'KS' },
  { county: 'Rooks', state: 'Kansas', stateCode: 'KS' },
  { county: 'Rush', state: 'Kansas', stateCode: 'KS' },
  { county: 'Russell', state: 'Kansas', stateCode: 'KS' },
  { county: 'Saline', state: 'Kansas', stateCode: 'KS' },
  { county: 'Scott', state: 'Kansas', stateCode: 'KS' },
  { county: 'Sedgwick', state: 'Kansas', stateCode: 'KS' },
  { county: 'Seward', state: 'Kansas', stateCode: 'KS' },
  { county: 'Shawnee', state: 'Kansas', stateCode: 'KS' },
  { county: 'Sheridan', state: 'Kansas', stateCode: 'KS' },
  { county: 'Sherman', state: 'Kansas', stateCode: 'KS' },
  { county: 'Smith', state: 'Kansas', stateCode: 'KS' },
  { county: 'Stafford', state: 'Kansas', stateCode: 'KS' },
  { county: 'Stanton', state: 'Kansas', stateCode: 'KS' },
  { county: 'Stevens', state: 'Kansas', stateCode: 'KS' },
  { county: 'Sumner', state: 'Kansas', stateCode: 'KS' },
  { county: 'Thomas', state: 'Kansas', stateCode: 'KS' },
  { county: 'Trego', state: 'Kansas', stateCode: 'KS' },
  { county: 'Wabaunsee', state: 'Kansas', stateCode: 'KS' },
  { county: 'Wallace', state: 'Kansas', stateCode: 'KS' },
  { county: 'Washington', state: 'Kansas', stateCode: 'KS' },
  { county: 'Wichita', state: 'Kansas', stateCode: 'KS' },
  { county: 'Wilson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Woodson', state: 'Kansas', stateCode: 'KS' },
  { county: 'Wyandotte', state: 'Kansas', stateCode: 'KS' },

  // South Dakota
  { county: 'Aurora', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Beadle', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Bennett', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Bon Homme', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Brookings', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Brown', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Brule', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Buffalo', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Butte', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Campbell', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Charles Mix', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Clark', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Clay', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Codington', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Corson', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Custer', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Davison', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Day', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Deuel', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Dewey', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Douglas', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Edmunds', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Fall River', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Faulk', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Grant', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Gregory', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Haakon', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Hamlin', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Hand', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Hanson', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Harding', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Hughes', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Hutchinson', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Hyde', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Jackson', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Jerauld', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Jones', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Kingsbury', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Lake', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Lawrence', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Lincoln', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Lyman', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Marshall', state: 'South Dakota', stateCode: 'SD' },
  { county: 'McCook', state: 'South Dakota', stateCode: 'SD' },
  { county: 'McPherson', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Meade', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Mellette', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Miner', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Minnehaha', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Moody', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Oglala Lakota', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Pennington', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Perkins', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Potter', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Roberts', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Sanborn', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Spink', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Stanley', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Sully', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Todd', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Tripp', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Turner', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Union', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Walworth', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Yankton', state: 'South Dakota', stateCode: 'SD' },
  { county: 'Ziebach', state: 'South Dakota', stateCode: 'SD' },

  // North Dakota
  { county: 'Adams', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Barnes', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Benson', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Billings', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Bottineau', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Bowman', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Burke', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Burleigh', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Cass', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Cavalier', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Dickey', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Divide', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Dunn', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Eddy', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Emmons', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Foster', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Golden Valley', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Grand Forks', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Grant', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Griggs', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Hettinger', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Kidder', state: 'North Dakota', stateCode: 'ND' },
  { county: 'LaMoure', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Logan', state: 'North Dakota', stateCode: 'ND' },
  { county: 'McHenry', state: 'North Dakota', stateCode: 'ND' },
  { county: 'McIntosh', state: 'North Dakota', stateCode: 'ND' },
  { county: 'McKenzie', state: 'North Dakota', stateCode: 'ND' },
  { county: 'McLean', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Mercer', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Morton', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Mountrail', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Nelson', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Oliver', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Pembina', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Pierce', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Ramsey', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Ransom', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Renville', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Richland', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Rolette', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Sargent', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Sheridan', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Sioux', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Slope', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Stark', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Steele', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Stutsman', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Towner', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Traill', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Walsh', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Ward', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Wells', state: 'North Dakota', stateCode: 'ND' },
  { county: 'Williams', state: 'North Dakota', stateCode: 'ND' },

  // Minnesota
  { county: 'Aitkin', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Anoka', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Becker', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Beltrami', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Benton', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Big Stone', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Blue Earth', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Brown', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Carlton', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Carver', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Cass', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Chippewa', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Chisago', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Clay', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Clearwater', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Cook', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Cottonwood', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Crow Wing', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Dakota', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Dodge', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Douglas', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Faribault', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Fillmore', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Freeborn', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Goodhue', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Grant', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Hennepin', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Houston', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Hubbard', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Isanti', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Itasca', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Jackson', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Kanabec', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Kandiyohi', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Kittson', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Koochiching', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Lac qui Parle', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Lake', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Lake of the Woods', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Le Sueur', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Lincoln', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Lyon', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Mahnomen', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Marshall', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Martin', state: 'Minnesota', stateCode: 'MN' },
  { county: 'McLeod', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Meeker', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Mille Lacs', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Morrison', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Mower', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Murray', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Nicollet', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Nobles', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Norman', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Olmsted', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Otter Tail', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Pennington', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Pine', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Pipestone', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Polk', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Pope', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Ramsey', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Red Lake', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Redwood', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Renville', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Rice', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Rock', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Roseau', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Scott', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Sherburne', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Sibley', state: 'Minnesota', stateCode: 'MN' },
  { county: 'St. Louis', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Stearns', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Steele', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Stevens', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Swift', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Todd', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Traverse', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Wabasha', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Wadena', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Waseca', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Washington', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Watonwan', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Wilkin', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Winona', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Wright', state: 'Minnesota', stateCode: 'MN' },
  { county: 'Yellow Medicine', state: 'Minnesota', stateCode: 'MN' },

  // Missouri
  { county: 'Adair', state: 'Missouri', stateCode: 'MO' },
  { county: 'Andrew', state: 'Missouri', stateCode: 'MO' },
  { county: 'Atchison', state: 'Missouri', stateCode: 'MO' },
  { county: 'Audrain', state: 'Missouri', stateCode: 'MO' },
  { county: 'Barry', state: 'Missouri', stateCode: 'MO' },
  { county: 'Barton', state: 'Missouri', stateCode: 'MO' },
  { county: 'Bates', state: 'Missouri', stateCode: 'MO' },
  { county: 'Benton', state: 'Missouri', stateCode: 'MO' },
  { county: 'Bollinger', state: 'Missouri', stateCode: 'MO' },
  { county: 'Boone', state: 'Missouri', stateCode: 'MO' },
  { county: 'Buchanan', state: 'Missouri', stateCode: 'MO' },
  { county: 'Butler', state: 'Missouri', stateCode: 'MO' },
  { county: 'Caldwell', state: 'Missouri', stateCode: 'MO' },
  { county: 'Callaway', state: 'Missouri', stateCode: 'MO' },
  { county: 'Camden', state: 'Missouri', stateCode: 'MO' },
  { county: 'Cape Girardeau', state: 'Missouri', stateCode: 'MO' },
  { county: 'Carroll', state: 'Missouri', stateCode: 'MO' },
  { county: 'Carter', state: 'Missouri', stateCode: 'MO' },
  { county: 'Cass', state: 'Missouri', stateCode: 'MO' },
  { county: 'Cedar', state: 'Missouri', stateCode: 'MO' },
  { county: 'Chariton', state: 'Missouri', stateCode: 'MO' },
  { county: 'Christian', state: 'Missouri', stateCode: 'MO' },
  { county: 'Clark', state: 'Missouri', stateCode: 'MO' },
  { county: 'Clay', state: 'Missouri', stateCode: 'MO' },
  { county: 'Clinton', state: 'Missouri', stateCode: 'MO' },
  { county: 'Cole', state: 'Missouri', stateCode: 'MO' },
  { county: 'Cooper', state: 'Missouri', stateCode: 'MO' },
  { county: 'Crawford', state: 'Missouri', stateCode: 'MO' },
  { county: 'Dade', state: 'Missouri', stateCode: 'MO' },
  { county: 'Dallas', state: 'Missouri', stateCode: 'MO' },
  { county: 'Daviess', state: 'Missouri', stateCode: 'MO' },
  { county: 'DeKalb', state: 'Missouri', stateCode: 'MO' },
  { county: 'Dent', state: 'Missouri', stateCode: 'MO' },
  { county: 'Douglas', state: 'Missouri', stateCode: 'MO' },
  { county: 'Dunklin', state: 'Missouri', stateCode: 'MO' },
  { county: 'Franklin', state: 'Missouri', stateCode: 'MO' },
  { county: 'Gasconade', state: 'Missouri', stateCode: 'MO' },
  { county: 'Gentry', state: 'Missouri', stateCode: 'MO' },
  { county: 'Greene', state: 'Missouri', stateCode: 'MO' },
  { county: 'Grundy', state: 'Missouri', stateCode: 'MO' },
  { county: 'Harrison', state: 'Missouri', stateCode: 'MO' },
  { county: 'Henry', state: 'Missouri', stateCode: 'MO' },
  { county: 'Hickory', state: 'Missouri', stateCode: 'MO' },
  { county: 'Holt', state: 'Missouri', stateCode: 'MO' },
  { county: 'Howard', state: 'Missouri', stateCode: 'MO' },
  { county: 'Howell', state: 'Missouri', stateCode: 'MO' },
  { county: 'Iron', state: 'Missouri', stateCode: 'MO' },
  { county: 'Jackson', state: 'Missouri', stateCode: 'MO' },
  { county: 'Jasper', state: 'Missouri', stateCode: 'MO' },
  { county: 'Jefferson', state: 'Missouri', stateCode: 'MO' },
  { county: 'Johnson', state: 'Missouri', stateCode: 'MO' },
  { county: 'Knox', state: 'Missouri', stateCode: 'MO' },
  { county: 'Laclede', state: 'Missouri', stateCode: 'MO' },
  { county: 'Lafayette', state: 'Missouri', stateCode: 'MO' },
  { county: 'Lawrence', state: 'Missouri', stateCode: 'MO' },
  { county: 'Lewis', state: 'Missouri', stateCode: 'MO' },
  { county: 'Lincoln', state: 'Missouri', stateCode: 'MO' },
  { county: 'Linn', state: 'Missouri', stateCode: 'MO' },
  { county: 'Livingston', state: 'Missouri', stateCode: 'MO' },
  { county: 'Macon', state: 'Missouri', stateCode: 'MO' },
  { county: 'Madison', state: 'Missouri', stateCode: 'MO' },
  { county: 'Maries', state: 'Missouri', stateCode: 'MO' },
  { county: 'Marion', state: 'Missouri', stateCode: 'MO' },
  { county: 'McDonald', state: 'Missouri', stateCode: 'MO' },
  { county: 'Mercer', state: 'Missouri', stateCode: 'MO' },
  { county: 'Miller', state: 'Missouri', stateCode: 'MO' },
  { county: 'Mississippi', state: 'Missouri', stateCode: 'MO' },
  { county: 'Moniteau', state: 'Missouri', stateCode: 'MO' },
  { county: 'Monroe', state: 'Missouri', stateCode: 'MO' },
  { county: 'Montgomery', state: 'Missouri', stateCode: 'MO' },
  { county: 'Morgan', state: 'Missouri', stateCode: 'MO' },
  { county: 'New Madrid', state: 'Missouri', stateCode: 'MO' },
  { county: 'Newton', state: 'Missouri', stateCode: 'MO' },
  { county: 'Nodaway', state: 'Missouri', stateCode: 'MO' },
  { county: 'Oregon', state: 'Missouri', stateCode: 'MO' },
  { county: 'Osage', state: 'Missouri', stateCode: 'MO' },
  { county: 'Ozark', state: 'Missouri', stateCode: 'MO' },
  { county: 'Pemiscot', state: 'Missouri', stateCode: 'MO' },
  { county: 'Perry', state: 'Missouri', stateCode: 'MO' },
  { county: 'Pettis', state: 'Missouri', stateCode: 'MO' },
  { county: 'Phelps', state: 'Missouri', stateCode: 'MO' },
  { county: 'Pike', state: 'Missouri', stateCode: 'MO' },
  { county: 'Platte', state: 'Missouri', stateCode: 'MO' },
  { county: 'Polk', state: 'Missouri', stateCode: 'MO' },
  { county: 'Pulaski', state: 'Missouri', stateCode: 'MO' },
  { county: 'Putnam', state: 'Missouri', stateCode: 'MO' },
  { county: 'Ralls', state: 'Missouri', stateCode: 'MO' },
  { county: 'Randolph', state: 'Missouri', stateCode: 'MO' },
  { county: 'Ray', state: 'Missouri', stateCode: 'MO' },
  { county: 'Reynolds', state: 'Missouri', stateCode: 'MO' },
  { county: 'Ripley', state: 'Missouri', stateCode: 'MO' },
  { county: 'Saline', state: 'Missouri', stateCode: 'MO' },
  { county: 'Schuyler', state: 'Missouri', stateCode: 'MO' },
  { county: 'Scotland', state: 'Missouri', stateCode: 'MO' },
  { county: 'Scott', state: 'Missouri', stateCode: 'MO' },
  { county: 'Shannon', state: 'Missouri', stateCode: 'MO' },
  { county: 'Shelby', state: 'Missouri', stateCode: 'MO' },
  { county: 'St. Charles', state: 'Missouri', stateCode: 'MO' },
  { county: 'St. Clair', state: 'Missouri', stateCode: 'MO' },
  { county: 'St. Francois', state: 'Missouri', stateCode: 'MO' },
  { county: 'St. Louis', state: 'Missouri', stateCode: 'MO' },
  { county: 'Ste. Genevieve', state: 'Missouri', stateCode: 'MO' },
  { county: 'Stoddard', state: 'Missouri', stateCode: 'MO' },
  { county: 'Stone', state: 'Missouri', stateCode: 'MO' },
  { county: 'Sullivan', state: 'Missouri', stateCode: 'MO' },
  { county: 'Taney', state: 'Missouri', stateCode: 'MO' },
  { county: 'Texas', state: 'Missouri', stateCode: 'MO' },
  { county: 'Vernon', state: 'Missouri', stateCode: 'MO' },
  { county: 'Warren', state: 'Missouri', stateCode: 'MO' },
  { county: 'Washington', state: 'Missouri', stateCode: 'MO' },
  { county: 'Wayne', state: 'Missouri', stateCode: 'MO' },
  { county: 'Webster', state: 'Missouri', stateCode: 'MO' },
  { county: 'Worth', state: 'Missouri', stateCode: 'MO' },
  { county: 'Wright', state: 'Missouri', stateCode: 'MO' },

  // Colorado
  { county: 'Adams', state: 'Colorado', stateCode: 'CO' },
  { county: 'Alamosa', state: 'Colorado', stateCode: 'CO' },
  { county: 'Arapahoe', state: 'Colorado', stateCode: 'CO' },
  { county: 'Archuleta', state: 'Colorado', stateCode: 'CO' },
  { county: 'Baca', state: 'Colorado', stateCode: 'CO' },
  { county: 'Bent', state: 'Colorado', stateCode: 'CO' },
  { county: 'Boulder', state: 'Colorado', stateCode: 'CO' },
  { county: 'Broomfield', state: 'Colorado', stateCode: 'CO' },
  { county: 'Chaffee', state: 'Colorado', stateCode: 'CO' },
  { county: 'Cheyenne', state: 'Colorado', stateCode: 'CO' },
  { county: 'Clear Creek', state: 'Colorado', stateCode: 'CO' },
  { county: 'Conejos', state: 'Colorado', stateCode: 'CO' },
  { county: 'Costilla', state: 'Colorado', stateCode: 'CO' },
  { county: 'Crowley', state: 'Colorado', stateCode: 'CO' },
  { county: 'Custer', state: 'Colorado', stateCode: 'CO' },
  { county: 'Delta', state: 'Colorado', stateCode: 'CO' },
  { county: 'Denver', state: 'Colorado', stateCode: 'CO' },
  { county: 'Dolores', state: 'Colorado', stateCode: 'CO' },
  { county: 'Douglas', state: 'Colorado', stateCode: 'CO' },
  { county: 'Eagle', state: 'Colorado', stateCode: 'CO' },
  { county: 'El Paso', state: 'Colorado', stateCode: 'CO' },
  { county: 'Elbert', state: 'Colorado', stateCode: 'CO' },
  { county: 'Fremont', state: 'Colorado', stateCode: 'CO' },
  { county: 'Garfield', state: 'Colorado', stateCode: 'CO' },
  { county: 'Gilpin', state: 'Colorado', stateCode: 'CO' },
  { county: 'Grand', state: 'Colorado', stateCode: 'CO' },
  { county: 'Gunnison', state: 'Colorado', stateCode: 'CO' },
  { county: 'Hinsdale', state: 'Colorado', stateCode: 'CO' },
  { county: 'Huerfano', state: 'Colorado', stateCode: 'CO' },
  { county: 'Jackson', state: 'Colorado', stateCode: 'CO' },
  { county: 'Jefferson', state: 'Colorado', stateCode: 'CO' },
  { county: 'Kiowa', state: 'Colorado', stateCode: 'CO' },
  { county: 'Kit Carson', state: 'Colorado', stateCode: 'CO' },
  { county: 'La Plata', state: 'Colorado', stateCode: 'CO' },
  { county: 'Lake', state: 'Colorado', stateCode: 'CO' },
  { county: 'Larimer', state: 'Colorado', stateCode: 'CO' },
  { county: 'Las Animas', state: 'Colorado', stateCode: 'CO' },
  { county: 'Lincoln', state: 'Colorado', stateCode: 'CO' },
  { county: 'Logan', state: 'Colorado', stateCode: 'CO' },
  { county: 'Mesa', state: 'Colorado', stateCode: 'CO' },
  { county: 'Mineral', state: 'Colorado', stateCode: 'CO' },
  { county: 'Moffat', state: 'Colorado', stateCode: 'CO' },
  { county: 'Montezuma', state: 'Colorado', stateCode: 'CO' },
  { county: 'Montrose', state: 'Colorado', stateCode: 'CO' },
  { county: 'Morgan', state: 'Colorado', stateCode: 'CO' },
  { county: 'Otero', state: 'Colorado', stateCode: 'CO' },
  { county: 'Ouray', state: 'Colorado', stateCode: 'CO' },
  { county: 'Park', state: 'Colorado', stateCode: 'CO' },
  { county: 'Phillips', state: 'Colorado', stateCode: 'CO' },
  { county: 'Pitkin', state: 'Colorado', stateCode: 'CO' },
  { county: 'Prowers', state: 'Colorado', stateCode: 'CO' },
  { county: 'Pueblo', state: 'Colorado', stateCode: 'CO' },
  { county: 'Rio Blanco', state: 'Colorado', stateCode: 'CO' },
  { county: 'Rio Grande', state: 'Colorado', stateCode: 'CO' },
  { county: 'Routt', state: 'Colorado', stateCode: 'CO' },
  { county: 'Saguache', state: 'Colorado', stateCode: 'CO' },
  { county: 'San Juan', state: 'Colorado', stateCode: 'CO' },
  { county: 'San Miguel', state: 'Colorado', stateCode: 'CO' },
  { county: 'Sedgwick', state: 'Colorado', stateCode: 'CO' },
  { county: 'Summit', state: 'Colorado', stateCode: 'CO' },
  { county: 'Teller', state: 'Colorado', stateCode: 'CO' },
  { county: 'Washington', state: 'Colorado', stateCode: 'CO' },
  { county: 'Weld', state: 'Colorado', stateCode: 'CO' },
  { county: 'Yuma', state: 'Colorado', stateCode: 'CO' },

  // Wyoming
  { county: 'Albany', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Big Horn', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Campbell', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Carbon', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Converse', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Crook', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Fremont', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Goshen', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Hot Springs', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Johnson', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Laramie', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Lincoln', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Natrona', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Niobrara', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Park', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Platte', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Sheridan', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Sublette', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Sweetwater', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Teton', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Uinta', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Washakie', state: 'Wyoming', stateCode: 'WY' },
  { county: 'Weston', state: 'Wyoming', stateCode: 'WY' },

  // Montana
  { county: 'Beaverhead', state: 'Montana', stateCode: 'MT' },
  { county: 'Big Horn', state: 'Montana', stateCode: 'MT' },
  { county: 'Blaine', state: 'Montana', stateCode: 'MT' },
  { county: 'Broadwater', state: 'Montana', stateCode: 'MT' },
  { county: 'Carbon', state: 'Montana', stateCode: 'MT' },
  { county: 'Carter', state: 'Montana', stateCode: 'MT' },
  { county: 'Cascade', state: 'Montana', stateCode: 'MT' },
  { county: 'Chouteau', state: 'Montana', stateCode: 'MT' },
  { county: 'Custer', state: 'Montana', stateCode: 'MT' },
  { county: 'Daniels', state: 'Montana', stateCode: 'MT' },
  { county: 'Dawson', state: 'Montana', stateCode: 'MT' },
  { county: 'Deer Lodge', state: 'Montana', stateCode: 'MT' },
  { county: 'Fallon', state: 'Montana', stateCode: 'MT' },
  { county: 'Fergus', state: 'Montana', stateCode: 'MT' },
  { county: 'Flathead', state: 'Montana', stateCode: 'MT' },
  { county: 'Gallatin', state: 'Montana', stateCode: 'MT' },
  { county: 'Garfield', state: 'Montana', stateCode: 'MT' },
  { county: 'Glacier', state: 'Montana', stateCode: 'MT' },
  { county: 'Golden Valley', state: 'Montana', stateCode: 'MT' },
  { county: 'Granite', state: 'Montana', stateCode: 'MT' },
  { county: 'Hill', state: 'Montana', stateCode: 'MT' },
  { county: 'Jefferson', state: 'Montana', stateCode: 'MT' },
  { county: 'Judith Basin', state: 'Montana', stateCode: 'MT' },
  { county: 'Lake', state: 'Montana', stateCode: 'MT' },
  { county: 'Lewis and Clark', state: 'Montana', stateCode: 'MT' },
  { county: 'Liberty', state: 'Montana', stateCode: 'MT' },
  { county: 'Lincoln', state: 'Montana', stateCode: 'MT' },
  { county: 'Madison', state: 'Montana', stateCode: 'MT' },
  { county: 'McCone', state: 'Montana', stateCode: 'MT' },
  { county: 'Meagher', state: 'Montana', stateCode: 'MT' },
  { county: 'Mineral', state: 'Montana', stateCode: 'MT' },
  { county: 'Missoula', state: 'Montana', stateCode: 'MT' },
  { county: 'Musselshell', state: 'Montana', stateCode: 'MT' },
  { county: 'Park', state: 'Montana', stateCode: 'MT' },
  { county: 'Petroleum', state: 'Montana', stateCode: 'MT' },
  { county: 'Phillips', state: 'Montana', stateCode: 'MT' },
  { county: 'Pondera', state: 'Montana', stateCode: 'MT' },
  { county: 'Powder River', state: 'Montana', stateCode: 'MT' },
  { county: 'Powell', state: 'Montana', stateCode: 'MT' },
  { county: 'Prairie', state: 'Montana', stateCode: 'MT' },
  { county: 'Ravalli', state: 'Montana', stateCode: 'MT' },
  { county: 'Richland', state: 'Montana', stateCode: 'MT' },
  { county: 'Roosevelt', state: 'Montana', stateCode: 'MT' },
  { county: 'Rosebud', state: 'Montana', stateCode: 'MT' },
  { county: 'Sanders', state: 'Montana', stateCode: 'MT' },
  { county: 'Sheridan', state: 'Montana', stateCode: 'MT' },
  { county: 'Silver Bow', state: 'Montana', stateCode: 'MT' },
  { county: 'Stillwater', state: 'Montana', stateCode: 'MT' },
  { county: 'Sweet Grass', state: 'Montana', stateCode: 'MT' },
  { county: 'Teton', state: 'Montana', stateCode: 'MT' },
  { county: 'Toole', state: 'Montana', stateCode: 'MT' },
  { county: 'Treasure', state: 'Montana', stateCode: 'MT' },
  { county: 'Valley', state: 'Montana', stateCode: 'MT' },
  { county: 'Wheatland', state: 'Montana', stateCode: 'MT' },
  { county: 'Wibaux', state: 'Montana', stateCode: 'MT' },
  { county: 'Yellowstone', state: 'Montana', stateCode: 'MT' },
]

// Build unique value key for each county entry
function getCountyKey(entry: { county: string; stateCode: string }) {
  return `${entry.county}, ${entry.stateCode}`
}

type CountyEntry = (typeof US_COUNTIES)[number]

// Group counties by state for display
const COUNTIES_BY_STATE = US_COUNTIES.reduce<
  Partial<Record<string, Array<CountyEntry>>>
>((acc, entry) => {
  if (!acc[entry.state]) acc[entry.state] = []
  acc[entry.state]!.push(entry)
  return acc
}, {})

const STATE_ORDER = Object.keys(COUNTIES_BY_STATE).sort()

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------
export interface CountyComboboxProps {
  /** Currently selected value in "County, ST" format, e.g. "Douglas, NE" */
  value?: string
  onChange: (value: string) => void
  placeholder?: string
  disabled?: boolean
  /** Extra class names on the trigger button */
  className?: string
  /** Show a clear button when a value is selected (default: true) */
  clearable?: boolean
}

export function CountyCombobox({
  value,
  onChange,
  placeholder = 'Search county...',
  disabled = false,
  className,
  clearable = true,
}: CountyComboboxProps) {
  const [open, setOpen] = React.useState(false)
  const [search, setSearch] = React.useState('')

  // Derive filtered list from search term
  const filteredByState = React.useMemo(() => {
    const q = search.toLowerCase().trim()
    if (!q) return COUNTIES_BY_STATE

    const result: Record<string, typeof US_COUNTIES> = {}
    for (const state of STATE_ORDER) {
      const matches = (COUNTIES_BY_STATE[state] ?? []).filter((entry) => {
        const label = getCountyKey(entry).toLowerCase()
        return (
          label.includes(q) ||
          entry.county.toLowerCase().includes(q) ||
          entry.stateCode.toLowerCase().includes(q) ||
          entry.state.toLowerCase().includes(q)
        )
      })
      if (matches.length) result[state] = matches
    }
    return result
  }, [search])

  const visibleStates = Object.keys(filteredByState).sort()
  const totalResults = visibleStates.reduce(
    (sum, s) => sum + (filteredByState[s] ?? []).length,
    0,
  )

  function handleSelect(key: string) {
    onChange(key === value ? '' : key)
    setOpen(false)
    setSearch('')
  }

  function handleClear(e: React.MouseEvent) {
    e.stopPropagation()
    onChange('')
  }

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          disabled={disabled}
          className={cn(
            'w-auto justify-between font-normal text-md',
            !value && 'text-muted-foreground',
            className,
          )}
        >
          <span className="flex items-center gap-2 truncate">
            <MapPin className="h-4 w-4 shrink-0 text-muted-foreground" />
            <span className="truncate">{value || placeholder}</span>
          </span>
          <span className="flex items-center gap-1 ml-2 shrink-0">
            {clearable && value && (
              <span
                role="button"
                tabIndex={0}
                aria-label="Clear selection"
                onClick={handleClear}
                onKeyDown={(e) => e.key === 'Enter' && handleClear(e as any)}
                className="rounded-sm p-0.5 hover:bg-muted cursor-pointer"
              >
                <X className="h-3.5 w-3.5 text-muted-foreground" />
              </span>
            )}
            <ChevronsUpDown className="h-4 w-4 text-muted-foreground opacity-50" />
          </span>
        </Button>
      </PopoverTrigger>

      <PopoverContent
        className="w-[var(--radix-popover-trigger-width)] p-0"
        align="start"
        sideOffset={4}
      >
        <Command shouldFilter={false}>
          <CommandInput
            placeholder="Search county or state..."
            value={search}
            onValueChange={setSearch}
          />
          <CommandList className="max-h-72">
            {totalResults === 0 ? (
              <CommandEmpty>No counties found.</CommandEmpty>
            ) : (
              visibleStates.map((state) => (
                <CommandGroup key={state} heading={state}>
                  {(filteredByState[state] ?? []).map((entry) => {
                    const key = getCountyKey(entry)
                    const isSelected = key === value
                    return (
                      <CommandItem
                        key={key}
                        value={key}
                        onSelect={() => handleSelect(key)}
                        className="cursor-pointer"
                      >
                        <Check
                          className={cn(
                            'mr-2 h-4 w-4',
                            isSelected ? 'opacity-100' : 'opacity-0',
                          )}
                        />
                        <span className="flex-1">{entry.county}</span>
                        <span className="ml-auto text-xs text-muted-foreground">
                          {entry.stateCode}
                        </span>
                      </CommandItem>
                    )
                  })}
                </CommandGroup>
              ))
            )}
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  )
}
